name: Test Tor on Linux with obfs4proxy

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Tor and obfs4proxy
        run: |
          sudo apt-get update
          sudo apt-get install tor obfs4proxy -y

      - name: Configure Tor
        run: |
          sudo sed -i 's/#SocksPort 9050/SocksPort 9060/g' /etc/tor/torrc
          sudo sed -i 's/#ControlPort 9051/ControlPort 9061/g' /etc/tor/torrc
          # password is "pass123"
          sudo sed -i 's/#HashedControlPassword/HashedControlPassword/g' /etc/tor/torrc
          # generate password hash
          pass_hash=$(tor --hash-password pass123 | tail -n 1)
          sudo sed -i "s|HashedControlPassword|$pass_hash|g" /etc/tor/torrc
          sudo service tor restart

      - name: Test Tor
        run: |
          echo "Waiting for Tor to start..."
          sleep 30
          for i in {1..5}; do
            original_ip=$(curl -s https://api.ipify.org)
            echo "Original IP: $original_ip"
            tor_ip=$(curl --socks5-hostname 127.0.0.1:9060 https://api.ipify.org)
            if [ $? -ne 0 ]; then
              echo "Error: Unable to connect to Tor"
              exit 1
            elif [ "$original_ip" != "$tor_ip" ]; then
              echo "Success: Tor IP is different from original IP"
              exit 0
            else
              echo "Retry #$i: Tor IP is the same as original IP"
              sleep 5
            fi
          done
          echo "Error: Unable to get a different IP address from Tor after multiple attempts"
          exit 1
      
      - name: New Ip
        run: |
          # authenticate and send signal to change IP
          echo "AUTHENTICATE \"pass123\"" | nc 127.0.0.1 9061
          echo "SIGNAL NEWNYM" | nc 127.0.0.1 9061
          echo "Waiting for Tor to change IP..."
          sleep 30
          for i in {1..3}; do
            new_tor_ip=$(curl --socks5-hostname 127.0.0.1:9060 https://api.ipify.org)
            if [ $? -ne 0 ]; then
              echo "Error: Unable to connect to Tor"
              exit 1
            elif [ "$tor_ip" != "$new_tor_ip" ]; then
              echo "Success: Tor IP has changed"
              exit 0
            else
              echo "Retry #$i: Tor IP is the same as before"
              sleep 5
            fi
          done
          echo "Error: Unable to get a different IP address from Tor after multiple attempts"
          exit 1