name: Test Tor on Linux with obfs4proxy

on:
  push:
    branches: [master]

jobs:
  test_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Tor and obfs4proxy
        run: |
          sudo apt-get update
          sudo apt-get install tor obfs4proxy -y

      - name: Start Tor
        run: sudo systemctl start tor