name: Test xtor

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Tor Expert Bundle
        run: |
         $url = 'https://archive.torproject.org/tor-package-archive/torbrowser/12.5a6/tor-expert-bundle-12.5a6-windows-x86_64.tar.gz'
         $output = 'tor-expert-bundle.tar.gz'
         Invoke-WebRequest -Uri $url -OutFile $output
         tar -xvzf $output -C .
         Get-ChildItem -Path .

  test_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Tor and obfs4proxy
        run: |
          sudo apt-get update
          sudo apt-get install -y tor obfs4proxy

      - name: Install poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run tests
        run: |
          poetry run pytest