name: Test Tor on Windows with obfs4proxy

on:
  push:
    branches: [master]

jobs:
  test_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download Tor Expert Bundle
        run: |
         $url = 'https://archive.torproject.org/tor-package-archive/torbrowser/12.5a6/tor-expert-bundle-12.5a6-windows-x86_64.tar.gz'
         $output = 'tor-expert-bundle.tar.gz'
         Invoke-WebRequest -Uri $url -OutFile $output
         tar -xvzf $output -C . 
         Get-ChildItem -Path .
         
  test_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Tor and obfs4proxy
        run: |
          sudo apt-get update
          sudo apt-get install tor obfs4proxy -y

      - name: Start Tor
        run: sudo systemctl start tor